<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Machine [
<!ELEMENT Machine (PunctChar*, Field*, FileChannel*, Register*, RegisterArray*, ConditionBit*, RAM*, Set*, Test*, Increment*, Shift*, Logical*, Arithmetic*, Branch*, TransferRtoR*, TransferRtoA*, TransferAtoR*, Decode*, SetCondBit*, IO*, MemoryAccess*, End, Comment*, EQU*, FetchSequence, MachineInstruction*, HighlightingInfo?, LoadingInfo?, IndexingInfo?, ProgramCounterInfo?, ModuleWindowsInfo?) >
<!ATTLIST Machine name CDATA "unnamed">
<!ELEMENT PunctChar EMPTY>
<!ATTLIST PunctChar char CDATA #REQUIRED use  (symbol|token|label|comment|pseudo|illegal) #REQUIRED>
<!ELEMENT Field (FieldValue*)>
<!ATTLIST Field name CDATA #REQUIRED type  (required|optional|ignored) #REQUIRED numBits CDATA #REQUIRED relativity (absolute|pcRelativePreIncr|pcRelativePostIncr) #REQUIRED defaultValue CDATA #REQUIRED signed (true|false) #REQUIRED id ID #REQUIRED>
<!ELEMENT FieldValue EMPTY>
<!ATTLIST FieldValue name CDATA #REQUIRED value CDATA #REQUIRED>
<!ELEMENT FileChannel EMPTY>
<!ATTLIST FileChannel file CDATA #REQUIRED id CDATA #REQUIRED>
<!ELEMENT Register EMPTY>
<!ATTLIST Register name CDATA #REQUIRED width CDATA #REQUIRED initialValue CDATA #REQUIRED readOnly (true|false) "false" id ID #REQUIRED>
<!ELEMENT RegisterArray (Register+)>
<!ATTLIST RegisterArray name CDATA #REQUIRED width CDATA #REQUIRED length CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT ConditionBit EMPTY>
<!ATTLIST ConditionBit name CDATA #REQUIRED bit CDATA #REQUIRED register IDREF #REQUIRED halt (true|false) "false" id ID #REQUIRED>
<!ELEMENT RAM EMPTY>
<!ATTLIST RAM name CDATA #REQUIRED length CDATA #REQUIRED id ID #REQUIRED cellSize CDATA "8">
<!ELEMENT Increment EMPTY>
<!ATTLIST Increment name CDATA #REQUIRED register IDREF #REQUIRED overflowBit IDREF #IMPLIED carryBit IDREF #IMPLIED delta CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Arithmetic EMPTY>
<!ATTLIST Arithmetic name CDATA #REQUIRED type (ADD|SUBTRACT|MULTIPLY|DIVIDE) #REQUIRED source1 IDREF #REQUIRED source2 IDREF #REQUIRED destination IDREF #REQUIRED overflowBit IDREF #IMPLIED  carryBit IDREF #IMPLIED  id ID #REQUIRED>
<!ELEMENT TransferRtoR EMPTY>
<!ATTLIST TransferRtoR name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT TransferRtoA EMPTY>
<!ATTLIST TransferRtoA name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED index IDREF #REQUIRED indexStart CDATA #IMPLIED indexNumBits CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT TransferAtoR EMPTY>
<!ATTLIST TransferAtoR name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED index IDREF #REQUIRED indexStart CDATA #IMPLIED indexNumBits CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT Shift EMPTY>
<!ATTLIST Shift name CDATA #REQUIRED source IDREF #REQUIRED destination IDREF #REQUIRED type (logical | arithmetic | cyclic) #REQUIRED direction (right | left) #REQUIRED distance CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Branch EMPTY>
<!ATTLIST Branch name CDATA #REQUIRED amount CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Logical EMPTY>
<!ATTLIST Logical name CDATA #REQUIRED source1 IDREF #REQUIRED source2 IDREF #REQUIRED destination IDREF #REQUIRED type (AND | OR | NAND | NOR | XOR | NOT) #REQUIRED id ID #REQUIRED>
<!ELEMENT Set EMPTY>
<!ATTLIST Set name CDATA #REQUIRED register IDREF #REQUIRED start CDATA #REQUIRED numBits CDATA #REQUIRED value CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Test EMPTY >
<!ATTLIST Test name CDATA #REQUIRED register IDREF #REQUIRED start CDATA #REQUIRED numBits CDATA #REQUIRED comparison (EQ | NE | LT | GT | LE | GE ) #REQUIRED value CDATA #REQUIRED omission CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Decode EMPTY >
<!ATTLIST Decode name CDATA #REQUIRED ir IDREF #REQUIRED id ID #REQUIRED>
<!ELEMENT IO EMPTY >
<!ATTLIST IO name CDATA #REQUIRED direction (input | output) #REQUIRED type (integer | ascii | unicode) #REQUIRED buffer IDREF #REQUIRED connection CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT MemoryAccess EMPTY >
<!ATTLIST MemoryAccess name CDATA #REQUIRED direction (read | write ) #REQUIRED memory IDREF #REQUIRED data IDREF #REQUIRED address IDREF #REQUIRED id ID #REQUIRED>
<!ELEMENT SetCondBit EMPTY >
<!ATTLIST SetCondBit name CDATA #REQUIRED bit IDREF #REQUIRED value (0 | 1) #REQUIRED id ID #REQUIRED>
<!ELEMENT End EMPTY>
<!ATTLIST End id ID #REQUIRED>
<!ELEMENT Comment EMPTY>
<!ATTLIST Comment name CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Microinstruction EMPTY>
<!ATTLIST Microinstruction microRef IDREF #REQUIRED>
<!ELEMENT MachineInstruction (Microinstruction*)>
<!ATTLIST MachineInstruction name CDATA #REQUIRED opcode CDATA #REQUIRED instructionFormat CDATA #REQUIRED assemblyFormat CDATA #REQUIRED instructionColors CDATA #REQUIRED assemblyColors CDATA #REQUIRED>
<!ELEMENT FetchSequence (Microinstruction*) >
<!ELEMENT EQU EMPTY>
<!ATTLIST EQU name CDATA #REQUIRED value CDATA #REQUIRED>
<!ELEMENT HighlightingInfo (RegisterRAMPair*)>
<!ELEMENT RegisterRAMPair EMPTY>
<!ATTLIST RegisterRAMPair register IDREF #REQUIRED ram IDREF #REQUIRED dynamic (true|false) #REQUIRED>
<!ELEMENT LoadingInfo EMPTY>
<!ATTLIST LoadingInfo ram IDREF #IMPLIED startingAddress CDATA "0">
<!ELEMENT IndexingInfo EMPTY>
<!ATTLIST IndexingInfo indexFromRight CDATA "false">
<!ELEMENT ProgramCounterInfo EMPTY>
<!ATTLIST ProgramCounterInfo programCounter IDREF #REQUIRED>
<!ELEMENT ModuleWindowsInfo ((RegisterWindowInfo | RegisterArrayWindowInfo | RAMWindowInfo)*) >
<!ELEMENT RegisterWindowInfo EMPTY>
<!ATTLIST RegisterWindowInfo top CDATA "50" left CDATA "50" width CDATA "300" height CDATA "150" base (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode)  "Decimal">
<!ELEMENT RegisterArrayWindowInfo EMPTY>
<!ATTLIST RegisterArrayWindowInfo array IDREF #REQUIRED top CDATA "50" left CDATA "50" width CDATA "300" height CDATA "150" base (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode) "Decimal">
<!ELEMENT RAMWindowInfo EMPTY>
<!ATTLIST RAMWindowInfo ram IDREF #REQUIRED cellSize CDATA "1" top CDATA "50" left CDATA "50" width CDATA "450" height CDATA "450" contentsbase (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode) "Decimal" addressbase (Decimal|Binary|Hexadecimal) "Decimal">
]>

<Machine name="Machine2" >
	<!--............. Punctuation Options .............-->
	<PunctChar char="!" use="symbol" />
	<PunctChar char="#" use="symbol" />
	<PunctChar char="$" use="symbol" />
	<PunctChar char="%" use="symbol" />
	<PunctChar char="&amp;" use="symbol" />
	<PunctChar char="^" use="symbol" />
	<PunctChar char="_" use="symbol" />
	<PunctChar char="`" use="symbol" />
	<PunctChar char="*" use="symbol" />
	<PunctChar char="?" use="symbol" />
	<PunctChar char="@" use="symbol" />
	<PunctChar char="~" use="symbol" />
	<PunctChar char="+" use="symbol" />
	<PunctChar char="-" use="symbol" />
	<PunctChar char="(" use="token" />
	<PunctChar char=")" use="token" />
	<PunctChar char="," use="token" />
	<PunctChar char="/" use="token" />
	<PunctChar char="=" use="token" />
	<PunctChar char="[" use="token" />
	<PunctChar char="\" use="token" />
	<PunctChar char="]" use="token" />
	<PunctChar char="{" use="token" />
	<PunctChar char="|" use="token" />
	<PunctChar char="}" use="token" />
	<PunctChar char="." use="pseudo" />
	<PunctChar char=":" use="label" />
	<PunctChar char=";" use="comment" />

	<!--......... machine instruction fields ............-->
	<Field name="I" type="required" numBits="1" relativity="absolute" signed="false" defaultValue="0" id="model.Field3ea922b7">
	</Field>
	<Field name="OP16" type="required" numBits="16" relativity="absolute" signed="false" defaultValue="0" id="model.Field1159852f">
	</Field>
	<Field name="OP3" type="required" numBits="3" relativity="absolute" signed="false" defaultValue="0" id="model.Field7115ab47">
	</Field>
	<Field name="ADDR12" type="required" numBits="12" relativity="absolute" signed="false" defaultValue="0" id="model.Field75407e51">
	</Field>

	<!--............. FileChannels .................-->
	<!-- none -->

	<!--............. registers .....................-->
	<Register name="AC" width="16" initialValue="0" readOnly="false" id="model.module.Register20b46d4" />
	<Register name="AR" width="12" initialValue="0" readOnly="false" id="model.module.Register5f26cb47" />
	<Register name="DR" width="16" initialValue="0" readOnly="false" id="model.module.Register3351c77" />
	<Register name="E" width="1" initialValue="0" readOnly="false" id="model.module.Register757158b6" />
	<Register name="I" width="1" initialValue="0" readOnly="false" id="model.module.Register2d149d2a" />
	<Register name="INPR" width="8" initialValue="0" readOnly="false" id="model.module.Register4401073c" />
	<Register name="IR" width="16" initialValue="0" readOnly="false" id="model.module.Register6f7c6d6f" />
	<Register name="OUTR" width="8" initialValue="0" readOnly="false" id="model.module.Register10b73cde" />
	<Register name="PC" width="12" initialValue="0" readOnly="false" id="model.module.Register19430e2f" />
	<Register name="S" width="1" initialValue="0" readOnly="false" id="model.module.Register55b7d2dc" />
	<Register name="TR" width="16" initialValue="0" readOnly="false" id="model.module.Register592cca10" />

	<!--............. register arrays ...............-->
	<!-- none -->

	<!--............. condition bits ................-->
	<ConditionBit name="E" bit="0" register="model.module.Register757158b6" halt="false" id="model.module.ConditionBit70d45c27" />
	<ConditionBit name="S" bit="0" register="model.module.Register55b7d2dc" halt="true" id="model.module.ConditionBit71e70664" />

	<!--............. rams ..........................-->
	<RAM name="M" length="4096" cellSize="16" id="model.module.RAM1aad0bb6" />

	<!--............. set ...........................-->
	<Set name="AC&lt;-0" register="model.module.Register20b46d4" start="0" numBits="16" value="0" id="model.microinstruction.CpusimSet25ee2eb9" />
	<Set name="E&lt;-0" register="model.module.Register757158b6" start="0" numBits="1" value="0" id="model.microinstruction.CpusimSet77896b47" />
	<Set name="S&lt;-1" register="model.module.Register55b7d2dc" start="0" numBits="1" value="1" id="model.microinstruction.CpusimSet3e9487f4" />

	<!--............. test ..........................-->
	<Test name="IF AC(15)=0" register="model.module.Register20b46d4" start="15" numBits="1" comparison="NE" value="0" omission="1" id="model.microinstruction.Test4c96cb2b" />
	<Test name="IF AC(15)=1" register="model.module.Register20b46d4" start="15" numBits="1" comparison="NE" value="1" omission="1" id="model.microinstruction.Test18d9afe6" />
	<Test name="IF AC=0" register="model.module.Register20b46d4" start="0" numBits="16" comparison="NE" value="0" omission="1" id="model.microinstruction.Test24b62ce9" />
	<Test name="IF DR=0" register="model.module.Register3351c77" start="0" numBits="16" comparison="NE" value="0" omission="1" id="model.microinstruction.Test3e87b4ac" />
	<Test name="IF E=0" register="model.module.Register757158b6" start="0" numBits="1" comparison="NE" value="0" omission="1" id="model.microinstruction.Test4432efc4" />
	<Test name="IF I !=0 " register="model.module.Register2d149d2a" start="0" numBits="1" comparison="EQ" value="0" omission="1" id="model.microinstruction.Test1141de3b" />

	<!--............. increment .....................-->
	<Increment name="AC&lt;-AC+1" register="model.module.Register20b46d4" delta="1" id="model.microinstruction.Increment485799e" />
	<Increment name="AR&lt;-AR+1" register="model.module.Register5f26cb47" delta="1" id="model.microinstruction.Increment7a49f76" />
	<Increment name="DR&lt;-DR+1" register="model.module.Register3351c77" delta="1" id="model.microinstruction.Increment543b0c89" />
	<Increment name="PC&lt;-PC+1" register="model.module.Register19430e2f" delta="1" id="model.microinstruction.Increment4b14b033" />

	<!--............. shift .........................-->
	<Shift name="AC&lt;-SHL AC" type="logical" source="model.module.Register20b46d4" destination="model.module.Register20b46d4" direction="left" distance="1" id="model.microinstruction.Shift64f26946" />
	<Shift name="AC&lt;-SHR AC" type="logical" source="model.module.Register20b46d4" destination="model.module.Register20b46d4" direction="right" distance="1" id="model.microinstruction.Shift470e1581" />

	<!--............. logical .......................-->
	<Logical name="AC&lt;-AC'" type="NOT" source1="model.module.Register20b46d4" source2="model.module.Register20b46d4" destination="model.module.Register20b46d4" id="model.microinstruction.Logical4bdd16ad" />
	<Logical name="AC&lt;-AC^DR" type="AND" source1="model.module.Register20b46d4" source2="model.module.Register3351c77" destination="model.module.Register20b46d4" id="model.microinstruction.Logical2526a2cd" />
	<Logical name="E&lt;-E'" type="NOT" source1="model.module.Register757158b6" source2="model.module.Register757158b6" destination="model.module.Register757158b6" id="model.microinstruction.Logical52694776" />

	<!--............. arithmetic ....................-->
	<Arithmetic name="AC&lt;-AC+DR,E&lt;-COUT" type="ADD" source1="model.module.Register20b46d4" source2="model.module.Register3351c77" destination="model.module.Register20b46d4" carryBit="model.module.ConditionBit70d45c27" id="model.microinstruction.Arithmetic657ce2a7" />

	<!--............. branch ........................-->
	<!-- none -->

	<!--............. transferRtoR ..................-->
	<TransferRtoR name="AC(0)&lt;-E" source="model.module.Register757158b6" srcStartBit="0" dest="model.module.Register20b46d4" destStartBit="0" numBits="1" id="model.microinstruction.TransferRtoR46b7f8db" />
	<TransferRtoR name="AC(15)&lt;-E" source="model.module.Register757158b6" srcStartBit="0" dest="model.module.Register20b46d4" destStartBit="15" numBits="1" id="model.microinstruction.TransferRtoR56971a0a" />
	<TransferRtoR name="AC&lt;-DR" source="model.module.Register3351c77" srcStartBit="0" dest="model.module.Register20b46d4" destStartBit="0" numBits="16" id="model.microinstruction.TransferRtoR4e5da559" />
	<TransferRtoR name="AR&lt;-IR(0-11)" source="model.module.Register6f7c6d6f" srcStartBit="0" dest="model.module.Register5f26cb47" destStartBit="0" numBits="12" id="model.microinstruction.TransferRtoR4cb61fef" />
	<TransferRtoR name="AR&lt;-PC" source="model.module.Register19430e2f" srcStartBit="0" dest="model.module.Register5f26cb47" destStartBit="0" numBits="12" id="model.microinstruction.TransferRtoR35be5782" />
	<TransferRtoR name="E&lt;-TR(0)" source="model.module.Register592cca10" srcStartBit="0" dest="model.module.Register757158b6" destStartBit="0" numBits="1" id="model.microinstruction.TransferRtoR5b974c75" />
	<TransferRtoR name="E&lt;-TR(15)" source="model.module.Register592cca10" srcStartBit="15" dest="model.module.Register757158b6" destStartBit="0" numBits="1" id="model.microinstruction.TransferRtoR78434d33" />
	<TransferRtoR name="I&lt;-IR(12)" source="model.module.Register6f7c6d6f" srcStartBit="12" dest="model.module.Register2d149d2a" destStartBit="0" numBits="1" id="model.microinstruction.TransferRtoR4766cb3" />
	<TransferRtoR name="PC&lt;-AR" source="model.module.Register5f26cb47" srcStartBit="0" dest="model.module.Register19430e2f" destStartBit="0" numBits="12" id="model.microinstruction.TransferRtoR433329f8" />
	<TransferRtoR name="TR(0)&lt;-AC(0)" source="model.module.Register20b46d4" srcStartBit="0" dest="model.module.Register592cca10" destStartBit="0" numBits="1" id="model.microinstruction.TransferRtoR22a6310f" />
	<TransferRtoR name="TR(15)&lt;-AC(15)" source="model.module.Register20b46d4" srcStartBit="15" dest="model.module.Register592cca10" destStartBit="15" numBits="1" id="model.microinstruction.TransferRtoR40eecabd" />

	<!--............. transferRtoA ..................-->
	<!-- none -->

	<!--............. transferAtoR ..................-->
	<!-- none -->

	<!--............. decode ........................-->
	<Decode name="DECODE IR" ir="model.module.Register6f7c6d6f" id="model.microinstruction.Decode774a25e7" />

	<!--............. set condition bit .............-->
	<!-- none -->

	<!--............. io ............................-->
	<IO name="INP" direction="input" type="integer" buffer="model.module.Register20b46d4" connection="[Console]" id="model.microinstruction.IO2decae1f" />
	<IO name="OUT" direction="output" type="integer" buffer="model.module.Register20b46d4" connection="[Console]" id="model.microinstruction.IO3ed1cce4" />

	<!--............. memory access .................-->
	<MemoryAccess name="AR&lt;-M[AR]" direction="read" memory="model.module.RAM1aad0bb6" data="model.module.Register5f26cb47" address="model.module.Register5f26cb47" id="model.microinstruction.MemoryAccess85c52a1" />
	<MemoryAccess name="DR&lt;-M[AR]" direction="read" memory="model.module.RAM1aad0bb6" data="model.module.Register3351c77" address="model.module.Register5f26cb47" id="model.microinstruction.MemoryAccess2e9f2b50" />
	<MemoryAccess name="IR&lt;-M[AR]" direction="read" memory="model.module.RAM1aad0bb6" data="model.module.Register6f7c6d6f" address="model.module.Register5f26cb47" id="model.microinstruction.MemoryAccess664bf4ca" />
	<MemoryAccess name="M[AR]&lt;-AC" direction="write" memory="model.module.RAM1aad0bb6" data="model.module.Register20b46d4" address="model.module.Register5f26cb47" id="model.microinstruction.MemoryAccess564db20b" />
	<MemoryAccess name="M[AR]&lt;-DR" direction="write" memory="model.module.RAM1aad0bb6" data="model.module.Register3351c77" address="model.module.Register5f26cb47" id="model.microinstruction.MemoryAccess3c6e2b39" />
	<MemoryAccess name="M[AR]&lt;-PC" direction="write" memory="model.module.RAM1aad0bb6" data="model.module.Register19430e2f" address="model.module.Register5f26cb47" id="model.microinstruction.MemoryAccess6bfc524f" />

	<!--............. end ...........................-->
	<End id="model.microinstruction.End52a8065e" />

	<!--............. comment ...........................-->
	<!-- none -->

	<!--............. global equs ..................-->
	<!-- none -->

	<!--............. fetch sequence ................-->
	<FetchSequence>
		<Microinstruction microRef="model.microinstruction.TransferRtoR35be5782" />
		<Microinstruction microRef="model.microinstruction.MemoryAccess664bf4ca" />
		<Microinstruction microRef="model.microinstruction.Increment4b14b033" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR4cb61fef" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR4766cb3" />
		<Microinstruction microRef="model.microinstruction.Test1141de3b" />
		<Microinstruction microRef="model.microinstruction.MemoryAccess85c52a1" />
		<Microinstruction microRef="model.microinstruction.Decode774a25e7" />
	</FetchSequence>

	<!--............. machine instructions ..........-->

	<MachineInstruction name="SZE" opcode="e002" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#eaaeb4" assemblyColors="#eaaeb4" >
		<Microinstruction microRef="model.microinstruction.Test4432efc4" />
		<Microinstruction microRef="model.microinstruction.Increment4b14b033" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="SZA" opcode="e004" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#b495bc" assemblyColors="#b495bc" >
		<Microinstruction microRef="model.microinstruction.Test24b62ce9" />
		<Microinstruction microRef="model.microinstruction.Increment4b14b033" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="SNA" opcode="e008" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#d2acef" assemblyColors="#d2acef" >
		<Microinstruction microRef="model.microinstruction.Test18d9afe6" />
		<Microinstruction microRef="model.microinstruction.Increment4b14b033" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="SPA" opcode="e010" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#e18482" assemblyColors="#e18482" >
		<Microinstruction microRef="model.microinstruction.Test4c96cb2b" />
		<Microinstruction microRef="model.microinstruction.Increment4b14b033" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="CIL" opcode="e040" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#a6afc8" assemblyColors="#a6afc8" >
		<Microinstruction microRef="model.microinstruction.TransferRtoR40eecabd" />
		<Microinstruction microRef="model.microinstruction.Shift64f26946" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR46b7f8db" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR78434d33" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="INC" opcode="e020" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#ada180" assemblyColors="#ada180" >
		<Microinstruction microRef="model.microinstruction.Increment485799e" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="CIR" opcode="e080" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#d6dfb9" assemblyColors="#d6dfb9" >
		<Microinstruction microRef="model.microinstruction.TransferRtoR22a6310f" />
		<Microinstruction microRef="model.microinstruction.Shift470e1581" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR56971a0a" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR5b974c75" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="CME" opcode="e100" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#fb8ca3" assemblyColors="#fb8ca3" >
		<Microinstruction microRef="model.microinstruction.Logical52694776" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="CLE" opcode="e400" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#bfebcf" assemblyColors="#bfebcf" >
		<Microinstruction microRef="model.microinstruction.CpusimSet77896b47" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="CLA" opcode="e800" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#c0fbfc" assemblyColors="#c0fbfc" >
		<Microinstruction microRef="model.microinstruction.CpusimSet25ee2eb9" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="CMA" opcode="e200" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#c5bfc6" assemblyColors="#c5bfc6" >
		<Microinstruction microRef="model.microinstruction.Logical4bdd16ad" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="OUT" opcode="f400" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#94a4b6" assemblyColors="#94a4b6" >
		<Microinstruction microRef="model.microinstruction.IO3ed1cce4" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="INP" opcode="f800" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#cca2d3" assemblyColors="#cca2d3" >
		<Microinstruction microRef="model.microinstruction.IO2decae1f" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="ISZ" opcode="6" instructionFormat="OP3 I ADDR12" assemblyFormat="OP3 I ADDR12" instructionColors="#9cbea8 #e3f7dd #e59eee" assemblyColors="#9cbea8 #e3f7dd #e59eee" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess2e9f2b50" />
		<Microinstruction microRef="model.microinstruction.Increment543b0c89" />
		<Microinstruction microRef="model.microinstruction.MemoryAccess3c6e2b39" />
		<Microinstruction microRef="model.microinstruction.Test3e87b4ac" />
		<Microinstruction microRef="model.microinstruction.Increment4b14b033" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="BUN" opcode="4" instructionFormat="OP3 I ADDR12" assemblyFormat="OP3 I ADDR12" instructionColors="#bbbaae #88a6fc #dcf7b5" assemblyColors="#bbbaae #88a6fc #dcf7b5" >
		<Microinstruction microRef="model.microinstruction.TransferRtoR433329f8" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="STA" opcode="3" instructionFormat="OP3 I ADDR12" assemblyFormat="OP3 I ADDR12" instructionColors="#e1fb87 #d5a8f5 #c3988c" assemblyColors="#e1fb87 #d5a8f5 #c3988c" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess564db20b" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="LDA" opcode="2" instructionFormat="OP3 I ADDR12" assemblyFormat="OP3 I ADDR12" instructionColors="#e9b79c #a3e9f2 #babad3" assemblyColors="#e9b79c #a3e9f2 #babad3" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess2e9f2b50" />
		<Microinstruction microRef="model.microinstruction.TransferRtoR4e5da559" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="ADD" opcode="1" instructionFormat="OP3 I ADDR12" assemblyFormat="OP3 I ADDR12" instructionColors="#fcf58f #80d38c #c4cbeb" assemblyColors="#fcf58f #80d38c #c4cbeb" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess2e9f2b50" />
		<Microinstruction microRef="model.microinstruction.Arithmetic657ce2a7" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<MachineInstruction name="HLT" opcode="e001" instructionFormat="OP16" assemblyFormat="OP16" instructionColors="#96c4a4" assemblyColors="#96c4a4" >
		<Microinstruction microRef="model.microinstruction.CpusimSet3e9487f4" />
	</MachineInstruction>

	<MachineInstruction name="AND" opcode="0" instructionFormat="OP3 I ADDR12" assemblyFormat="OP3 I ADDR12" instructionColors="#e3bedd #e0b0e4 #afbbb3" assemblyColors="#e3bedd #e0b0e4 #afbbb3" >
		<Microinstruction microRef="model.microinstruction.MemoryAccess2e9f2b50" />
		<Microinstruction microRef="model.microinstruction.Logical2526a2cd" />
		<Microinstruction microRef="model.microinstruction.End52a8065e" />
	</MachineInstruction>

	<!--............. highlighting info .............-->
	<HighlightingInfo>
	</HighlightingInfo>

	<!--............. loading info ..................-->
	<LoadingInfo ram="model.module.RAM1aad0bb6" startingAddress="38" />

	<!--............. indexing info ............-->
	<IndexingInfo indexFromRight="true" />

	<!--............. program counter info ..................-->

</Machine>
